import React from 'react';

const RoadmapPDF = React.forwardRef(({ data }, ref) => {
  if (!data) return null;

  return (
    <div ref={ref} className="p-6 text-left text-sm">
      <h2 className="text-2xl font-bold text-blue-700 mb-2">SkillSync – Learning Roadmap</h2>
      <p><strong>Match %:</strong> {data.matchPercent}%</p>
      <p><strong>Matched Skills:</strong> {data.matched.join(', ')}</p>
      <p><strong>Missing Skills:</strong> {data.missing.join(', ')}</p>

      <h3 className="text-lg text-green-700 mt-4 mb-2">📚 Week-by-Week Roadmap</h3>
      <ul className="list-disc ml-5">
        {data.roadmap.map((item, idx) => (
          <li key={idx}>
            <strong>Week {item.week}:</strong> Learn {item.skill} – {item.link}
          </li>
        ))}
      </ul>

      <p className="text-xs text-gray-500 mt-6">Generated by SkillSync</p>
    </div>
  );
});

export default RoadmapPDF;

